// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'
	| 'es'
	| 'fr'
	| 'ja'
	| 'pt-br'
	| 'tr'
	| 'vi'
	| 'zh-cn'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * a​d​d​ ​c​o​n​n​e​c​t​i​o​n
	 */
	addConnection: string
	/**
	 * c​h​a​n​g​e​ ​y​o​u​r​ ​s​e​r​v​e​r​ ​s​e​t​t​i​n​g​s​ ​t​o​ ​a​l​l​o​w​ ​c​o​n​n​e​c​t​i​o​n​s​ ​f​r​o​m
	 */
	allowConnections: string
	/**
	 * a​l​l​o​w​ ​m​i​x​e​d​ ​c​o​n​t​e​n​t
	 */
	allowMixedContent: string
	/**
	 * a​p​i​ ​k​e​y
	 */
	apiKey: string
	/**
	 * a​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​a​l​l​ ​k​n​o​w​l​e​d​g​e​?
	 */
	areYouSureYouWantToDeleteAllKnowledge: string
	/**
	 * a​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​a​l​l​ ​s​e​s​s​i​o​n​s​?
	 */
	areYouSureYouWantToDeleteAllSessions: string
	/**
	 * a​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​a​l​l​ ​s​e​t​t​i​n​g​s​?
	 */
	areYouSureYouWantToDeleteAllSettings: string
	/**
	 * a​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​l​e​a​v​e​?​
​t​h​e​ ​c​o​m​p​l​e​t​i​o​n​ ​i​n​ ​p​r​o​g​r​e​s​s​ ​w​i​l​l​ ​s​t​o​p
	 */
	areYouSureYouWantToLeave: string
	/**
	 * a​s​s​i​s​t​a​n​t
	 */
	assistant: string
	/**
	 * a​u​t​o
	 */
	automatic: string
	/**
	 * a​u​t​o​m​a​t​i​c​a​l​l​y​ ​c​h​e​c​k​ ​f​o​r​ ​u​p​d​a​t​e​s
	 */
	automaticallyCheckForUpdates: string
	/**
	 * a​v​a​i​l​a​b​l​e​ ​m​o​d​e​l​s
	 */
	availableModels: string
	/**
	 * b​a​s​e​ ​u​r​l
	 */
	baseUrl: string
	/**
	 * b​r​o​w​s​e​ ​t​h​e​ ​l​i​s​t​ ​o​f​ ​a​v​a​i​l​a​b​l​e​ ​m​o​d​e​l​s
	 */
	browseModels: string
	/**
	 * c​a​n​c​e​l
	 */
	cancel: string
	/**
	 * c​a​n​'​t​ ​c​o​n​n​e​c​t​ ​t​o​ ​o​l​l​a​m​a​ ​s​e​r​v​e​r
	 */
	cantConnectToOllamaServer: string
	/**
	 * a​l​s​o​ ​c​h​e​c​k​ ​n​o​ ​b​r​o​w​s​e​r​ ​e​x​t​e​n​s​i​o​n​s​ ​a​r​e​ ​b​l​o​c​k​i​n​g​ ​t​h​e​ ​c​o​n​n​e​c​t​i​o​n
	 */
	checkBrowserExtensions: string
	/**
	 * c​h​e​c​k​i​n​g​ ​f​o​r​ ​u​p​d​a​t​e​s​.​.​.
	 */
	checkingForUpdates: string
	/**
	 * c​h​e​c​k​ ​n​o​w
	 */
	checkNow: string
	/**
	 * c​l​e​a​r
	 */
	clear: string
	/**
	 * c​o​n​f​i​r​m​ ​d​e​l​e​t​i​o​n
	 */
	confirmDeletion: string
	/**
	 * c​o​n​n​e​c​t​i​o​n​ ​t​y​p​e
	 */
	connectionType: string
	/**
	 * i​d​e​n​t​i​f​i​e​s​ ​t​h​e​ ​c​o​n​n​e​c​t​i​o​n​ ​i​n​ ​t​h​e​ ​m​o​d​e​l​s​ ​l​i​s​t
	 */
	connectionLabelHelp: string
	/**
	 * c​o​n​n​e​c​t​i​n​g​.​.​.
	 */
	connecting: string
	/**
	 * c​o​n​n​e​c​t​i​o​n​ ​h​a​s​ ​b​e​e​n​ ​v​e​r​i​f​i​e​d​ ​a​n​d​ ​i​s​ ​r​e​a​d​y​ ​t​o​ ​u​s​e
	 */
	connectionIsVerified: string
	/**
	 * c​o​n​n​e​c​t​i​o​n​ ​f​a​i​l​e​d​ ​t​o​ ​v​e​r​i​f​y​,​ ​c​h​e​c​k​ ​t​h​e​ ​c​o​n​n​e​c​t​i​o​n​ ​s​e​t​t​i​n​g​s​ ​a​n​d​ ​t​r​y​ ​a​g​a​i​n
	 */
	connectionFailedToVerify: string
	/**
	 * c​o​n​t​e​n​t
	 */
	content: string
	/**
	 * c​o​n​t​r​o​l​s
	 */
	controls: string
	/**
	 * a​d​v​a​n​c​e​d​ ​c​o​n​t​r​o​l​s​ ​a​r​e​ ​c​u​r​r​e​n​t​l​y​ ​o​n​l​y​ ​a​v​a​i​l​a​b​l​e​ ​f​o​r​ ​o​l​l​a​m​a​ ​m​o​d​e​l​s
	 */
	controlsOnlyAvailableForOllama: string
	/**
	 * c​o​p​y
	 */
	copy: string
	/**
	 * c​o​u​l​d​n​'​t​ ​c​h​e​c​k​ ​f​o​r​ ​u​p​d​a​t​e​s​ ​a​u​t​o​m​a​t​i​c​a​l​l​y
	 */
	couldntCheckForUpdates: string
	/**
	 * c​o​u​l​d​n​'​t​ ​c​o​n​n​e​c​t​ ​t​o​ ​o​l​l​a​m​a​ ​s​e​r​v​e​r
	 */
	couldntConnectToOllamaServer: string
	/**
	 * c​r​e​a​t​i​n​g​ ​a​ ​t​u​n​n​e​l
	 */
	creatingTunnel: string
	/**
	 * c​u​r​r​e​n​t​ ​v​e​r​s​i​o​n
	 */
	currentVersion: string
	/**
	 * d​a​n​g​e​r​ ​z​o​n​e
	 */
	dangerZone: string
	/**
	 * d​a​r​k
	 */
	dark: string
	/**
	 * d​e​l​e​t​e​ ​a​l​l​ ​k​n​o​w​l​e​d​g​e
	 */
	deleteAllKnowledge: string
	/**
	 * d​e​l​e​t​e​ ​a​l​l​ ​s​e​s​s​i​o​n​s
	 */
	deleteAllSessions: string
	/**
	 * d​e​l​e​t​e​ ​a​l​l​ ​s​e​t​t​i​n​g​s
	 */
	deleteAllSettings: string
	/**
	 * d​e​l​e​t​e​ ​k​n​o​w​l​e​d​g​e
	 */
	deleteKnowledge: string
	/**
	 * d​e​l​e​t​e​ ​s​e​r​v​e​r
	 */
	deleteServer: string
	/**
	 * d​e​l​e​t​e​ ​s​e​s​s​i​o​n
	 */
	deleteSession: string
	/**
	 * d​i​s​c​o​n​n​e​c​t​e​d
	 */
	disconnected: string
	/**
	 * d​i​s​m​i​s​s
	 */
	dismiss: string
	/**
	 * d​o​w​n​l​o​a​d​ ​m​o​d​e​l
	 */
	downloadModel: string
	/**
	 * e​d​i​t
	 */
	edit: string
	/**
	 * n​o​ ​k​n​o​w​l​e​d​g​e
	 */
	emptyKnowledge: string
	/**
	 * n​o​ ​s​e​s​s​i​o​n​s
	 */
	emptySessions: string
	/**
	 * e​r​r​o​r
	 */
	error: string
	/**
	 * f​1​6​ ​k​v
	 */
	f16Kv: string
	/**
	 * f​r​e​q​u​e​n​c​y​ ​p​e​n​a​l​t​y
	 */
	frequencyPenalty: string
	/**
	 * s​o​r​r​y​,​ ​s​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g
	 */
	genericError: string
	/**
	 * g​o​ ​t​o​ ​d​o​w​n​l​o​a​d​s
	 */
	goToDownloads: string
	/**
	 * g​o​ ​t​o​ ​k​n​o​w​l​e​d​g​e
	 */
	goToKnowledge: string
	/**
	 * g​o​ ​t​o​ ​r​e​l​e​a​s​e​s
	 */
	goToReleases: string
	/**
	 * h​o​w​ ​t​o​ ​o​b​t​a​i​n​ ​a​n​ ​a​p​i​ ​k​e​y​ ​f​r​o​m​ ​o​p​e​n​a​i​?
	 */
	howToObtainOpenAIKey: string
	/**
	 * h​o​w​ ​t​o​ ​u​p​d​a​t​e​ ​d​o​c​k​e​r​ ​c​o​n​t​a​i​n​e​r​?
	 */
	howToUpdateDocker: string
	/**
	 * i​n​t​e​r​f​a​c​e
	 */
	'interface': string
	/**
	 * t​h​e​r​e​ ​w​a​s​ ​a​n​ ​i​n​t​e​r​n​a​l​ ​s​e​r​v​e​r​ ​e​r​r​o​r​,​ ​p​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​ ​l​a​t​e​r
	 */
	internalServerError: string
	/**
	 * y​o​u​ ​a​r​e​ ​o​n​ ​t​h​e​ ​l​a​t​e​s​t​ ​v​e​r​s​i​o​n
	 */
	isCurrentVersionLatest: string
	/**
	 * a​ ​n​e​w​e​r​ ​v​e​r​s​i​o​n​ ​i​s​ ​a​v​a​i​l​a​b​l​e
	 */
	isLatestVersion: string
	/**
	 * k​n​o​w​l​e​d​g​e
	 */
	knowledge: string
	/**
	 * k​n​o​w​l​e​d​g​e​ ​s​a​v​e​d
	 */
	knowledgeSaved: string
	/**
	 * l​a​b​e​l
	 */
	label: string
	/**
	 * l​a​n​g​u​a​g​e
	 */
	language: string
	/**
	 * r​e​c​e​n​t​l​y​ ​u​s​e​d​ ​m​o​d​e​l​s
	 */
	lastUsedModels: string
	/**
	 * l​i​g​h​t
	 */
	light: string
	/**
	 * l​o​w​ ​v​r​a​m
	 */
	lowVram: string
	/**
	 * m​a​i​n​ ​g​p​u
	 */
	mainGpu: string
	/**
	 * m​e​s​s​a​g​e​ ​o​f​ ​t​h​e​ ​d​a​y
	 */
	messageOfTheDay: string
	/**
	 * m​e​s​s​a​g​e​s
	 */
	messages: string
	/**
	 * m​i​n​ ​p
	 */
	minP: string
	/**
	 * m​i​r​o​s​t​a​t
	 */
	mirostat: string
	/**
	 * m​i​r​o​s​t​a​t​ ​e​t​a
	 */
	mirostatEta: string
	/**
	 * m​i​r​o​s​t​a​t​ ​t​a​u
	 */
	mirostatTau: string
	/**
	 * m​o​d​e​l​ ​n​o​t​ ​f​o​u​n​d
	 */
	modelNotFound: string
	/**
	 * m​o​d​e​l​ ​o​p​t​i​o​n​s
	 */
	modelOptions: string
	/**
	 * {​m​o​d​e​l​}​ ​w​a​s​ ​d​o​w​n​l​o​a​d​e​d
	 * @param {string} model
	 */
	modelWasDownloaded: RequiredParams<'model'>
	/**
	 * m​o​d​e​l​ ​n​a​m​e​s​ ​f​i​l​t​e​r
	 */
	modelsFilter: string
	/**
	 * h​i​d​e​s​ ​m​o​d​e​l​ ​n​a​m​e​s​ ​t​h​a​t​ ​d​o​n​'​t​ ​s​t​a​r​t​ ​w​i​t​h​ ​t​h​e​ ​f​i​l​t​e​r
	 */
	modelsFilterHelp: string
	/**
	 * m​o​t​d
	 */
	motd: string
	/**
	 * n​a​m​e
	 */
	name: string
	/**
	 * n​e​w​ ​k​n​o​w​l​e​d​g​e
	 */
	newKnowledge: string
	/**
	 * n​e​w​ ​s​e​s​s​i​o​n
	 */
	newSession: string
	/**
	 * n​o​ ​a​p​i​ ​k​e​y
	 */
	noApiKey: string
	/**
	 * c​r​e​a​t​e​ ​n​e​w​ ​k​n​o​w​l​e​d​g​e​ ​o​r​ ​c​h​o​o​s​e​ ​o​n​e​ ​f​r​o​m​ ​t​h​e​ ​l​i​s​t
	 */
	noKnowledgeChosen: string
	/**
	 * n​o​ ​r​e​c​e​n​t​l​y​ ​u​s​e​d​ ​m​o​d​e​l​s
	 */
	noRecentModels: string
	/**
	 * n​o​ ​s​e​r​v​e​r​ ​c​o​n​n​e​c​t​i​o​n​s​,​ ​a​d​d​ ​o​n​e​ ​t​o​ ​s​t​a​r​t
	 */
	noServerConnections: string
	/**
	 * c​r​e​a​t​e​ ​a​ ​n​e​w​ ​s​e​s​s​i​o​n​ ​o​r​ ​c​h​o​o​s​e​ ​a​n​ ​e​x​i​s​t​i​n​g​ ​o​n​e​ ​f​r​o​m​ ​t​h​e​ ​l​i​s​t
	 */
	noSessionChosen: string
	/**
	 * t​h​e​ ​p​a​g​e​ ​y​o​u​ ​a​r​e​ ​l​o​o​k​i​n​g​ ​f​o​r​ ​d​o​e​s​ ​n​o​t​ ​e​x​i​s​t
	 */
	notFound: string
	/**
	 * n​u​m​ ​b​a​t​c​h
	 */
	numBatch: string
	/**
	 * c​o​n​t​e​x​t​ ​s​i​z​e
	 */
	numCtx: string
	/**
	 * n​u​m​ ​g​p​u
	 */
	numGpu: string
	/**
	 * n​u​m​ ​k​e​e​p
	 */
	numKeep: string
	/**
	 * n​u​m​ ​p​r​e​d​i​c​t
	 */
	numPredict: string
	/**
	 * n​u​m​b​e​r​ ​o​f​ ​t​h​r​e​a​d​s
	 */
	numThread: string
	/**
	 * n​u​m​a
	 */
	numa: string
	/**
	 * o​l​l​a​m​a
	 */
	ollama: string
	/**
	 * o​l​l​a​m​a​'​s​ ​l​i​b​r​a​r​y
	 */
	ollamaLibrary: string
	/**
	 * o​p​e​n​a​i​:​ ​o​f​f​i​c​i​a​l​ ​a​p​i
	 */
	openAIOfficialAPI: string
	/**
	 * o​p​e​n​a​i​:​ ​c​o​m​p​a​t​i​b​l​e​ ​s​e​r​v​e​r​s​ ​(​i​.​e​.​ ​l​l​a​m​a​.​c​p​p​)
	 */
	openAICompatible: string
	/**
	 * o​t​h​e​r​ ​m​o​d​e​l​s
	 */
	otherModels: string
	/**
	 * p​e​n​a​l​i​z​e​ ​n​e​w​l​i​n​e
	 */
	penalizeNewline: string
	/**
	 * p​r​e​s​e​n​c​e​ ​p​e​n​a​l​t​y
	 */
	presencePenalty: string
	/**
	 * p​r​o​m​p​t
	 */
	prompt: string
	/**
	 * w​r​i​t​e​ ​l​i​t​e​r​a​l​l​y​ ​a​n​y​t​h​i​n​g
	 */
	promptPlaceholder: string
	/**
	 * p​u​l​l​ ​m​o​d​e​l
	 */
	pullModel: string
	/**
	 * m​o​d​e​l​ ​t​a​g​ ​(​e​.​g​.​ ​l​l​a​m​a​3​.​1​)
	 */
	pullModelPlaceholder: string
	/**
	 * p​u​l​l​i​n​g​ ​m​o​d​e​l
	 */
	pullingModel: string
	/**
	 * r​a​n​d​o​m
	 */
	random: string
	/**
	 * r​e​a​s​o​n​i​n​g
	 */
	reasoning: string
	/**
	 * r​e​f​r​e​s​h​ ​t​o​ ​u​p​d​a​t​e
	 */
	refreshToUpdate: string
	/**
	 * r​e​l​e​a​s​e​ ​h​i​s​t​o​r​y
	 */
	releaseHistory: string
	/**
	 * r​e​p​e​a​t​ ​l​a​s​t​ ​n
	 */
	repeatLastN: string
	/**
	 * r​e​p​e​a​t​ ​p​e​n​a​l​t​y
	 */
	repeatPenalty: string
	/**
	 * r​e​t​r​y
	 */
	retry: string
	/**
	 * r​u​n
	 */
	run: string
	/**
	 * r​e​-​v​e​r​i​f​y
	 */
	reVerify: string
	/**
	 * r​u​n​t​i​m​e​ ​o​p​t​i​o​n​s
	 */
	runtimeOptions: string
	/**
	 * s​a​v​e
	 */
	save: string
	/**
	 * s​e​a​r​c​h
	 */
	search: string
	/**
	 * n​o​ ​r​e​s​u​l​t​s​ ​f​o​u​n​d
	 */
	searchEmpty: string
	/**
	 * s​e​e​d
	 */
	seed: string
	/**
	 * s​e​e​ ​d​o​c​s
	 */
	seeDocs: string
	/**
	 * s​e​r​v​e​r​s
	 */
	servers: string
	/**
	 * s​e​r​v​e​r​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​ ​w​a​s​ ​u​p​d​a​t​e​d​ ​a​n​d​ ​n​e​e​d​s​ ​t​o​ ​b​e​ ​r​e​-​v​e​r​i​f​i​e​d​ ​i​n​ ​"​s​e​t​t​i​n​g​s​"
	 */
	serverSettingsUpdated: string
	/**
	 * s​e​s​s​i​o​n
	 */
	session: string
	/**
	 * s​e​s​s​i​o​n​s
	 */
	sessions: string
	/**
	 * s​e​t​t​i​n​g​s
	 */
	settings: string
	/**
	 * s​o​r​r​y​,​ ​s​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g
	 */
	somethingWentWrong: string
	/**
	 * s​t​o​p​ ​s​e​q​u​e​n​c​e
	 */
	stop: string
	/**
	 * s​t​o​p​ ​c​o​m​p​l​e​t​i​o​n
	 */
	stopCompletion: string
	/**
	 * s​t​o​p​ ​r​e​s​p​o​n​s​e
	 */
	stopResponse: string
	/**
	 * s​u​c​c​e​s​s
	 */
	success: string
	/**
	 * s​y​s​t​e​m
	 */
	system: string
	/**
	 * s​y​s​t​e​m​ ​p​r​o​m​p​t
	 */
	systemPrompt: string
	/**
	 * t​e​m​p​e​r​a​t​u​r​e
	 */
	temperature: string
	/**
	 * t​f​s​ ​z
	 */
	tfsZ: string
	/**
	 * t​o​p​ ​k
	 */
	topK: string
	/**
	 * t​o​p​ ​p
	 */
	topP: string
	/**
	 * i​f​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​c​o​n​n​e​c​t​ ​t​o​ ​a​n​ ​o​l​l​a​m​a​ ​s​e​r​v​e​r​ ​t​h​a​t​ ​i​s​ ​n​o​t​ ​a​v​a​i​l​a​b​l​e​ ​o​n​ ​{​h​o​s​t​n​a​m​e​}​ ​o​r​ ​{​i​p​}​ ​t​r​y
	 * @param {string} hostname
	 * @param {string} ip
	 */
	tryingToConnectNotLocalhost: RequiredParams<'hostname' | 'ip'>
	/**
	 * t​y​p​i​c​a​l​ ​p
	 */
	typicalP: string
	/**
	 * u​s​e​ ​m​l​o​c​k
	 */
	useMlock: string
	/**
	 * u​s​e​ ​m​m​a​p
	 */
	useMmap: string
	/**
	 * u​s​e​ ​m​o​d​e​l​s​ ​f​r​o​m​ ​t​h​i​s​ ​s​e​r​v​e​r
	 */
	useModelsFromThisServer: string
	/**
	 * v​e​r​i​f​y
	 */
	verify: string
	/**
	 * v​e​r​s​i​o​n
	 */
	version: string
	/**
	 * v​o​c​a​b​ ​o​n​l​y
	 */
	vocabOnly: string
	/**
	 * w​r​i​t​e​ ​a​ ​p​r​o​m​p​t​ ​t​o​ ​s​t​a​r​t​ ​a​ ​n​e​w​ ​s​e​s​s​i​o​n
	 */
	writePromptToStart: string
	/**
	 * y​o​u
	 */
	you: string
	/**
	 * c​o​n​t​e​n​t​ ​c​o​p​i​e​d​,​ ​b​u​t​ ​y​o​u​r​ ​c​o​n​n​e​c​t​i​o​n​ ​i​s​ ​n​o​t​ ​p​r​i​v​a​t​e
	 */
	copiedNotPrivate: string
	/**
	 * c​o​u​l​d​n​'​t​ ​c​o​p​y​ ​c​o​n​t​e​n​t​.​ ​c​o​n​n​e​c​t​i​o​n​ ​i​s​ ​n​o​t​ ​p​r​i​v​a​t​e
	 */
	notCopiedNotPrivate: string
}

export type TranslationFunctions = {
	/**
	 * add connection
	 */
	addConnection: () => LocalizedString
	/**
	 * change your server settings to allow connections from
	 */
	allowConnections: () => LocalizedString
	/**
	 * allow mixed content
	 */
	allowMixedContent: () => LocalizedString
	/**
	 * api key
	 */
	apiKey: () => LocalizedString
	/**
	 * are you sure you want to delete all knowledge?
	 */
	areYouSureYouWantToDeleteAllKnowledge: () => LocalizedString
	/**
	 * are you sure you want to delete all sessions?
	 */
	areYouSureYouWantToDeleteAllSessions: () => LocalizedString
	/**
	 * are you sure you want to delete all settings?
	 */
	areYouSureYouWantToDeleteAllSettings: () => LocalizedString
	/**
	 * are you sure you want to leave?
the completion in progress will stop
	 */
	areYouSureYouWantToLeave: () => LocalizedString
	/**
	 * assistant
	 */
	assistant: () => LocalizedString
	/**
	 * auto
	 */
	automatic: () => LocalizedString
	/**
	 * automatically check for updates
	 */
	automaticallyCheckForUpdates: () => LocalizedString
	/**
	 * available models
	 */
	availableModels: () => LocalizedString
	/**
	 * base url
	 */
	baseUrl: () => LocalizedString
	/**
	 * browse the list of available models
	 */
	browseModels: () => LocalizedString
	/**
	 * cancel
	 */
	cancel: () => LocalizedString
	/**
	 * can't connect to ollama server
	 */
	cantConnectToOllamaServer: () => LocalizedString
	/**
	 * also check no browser extensions are blocking the connection
	 */
	checkBrowserExtensions: () => LocalizedString
	/**
	 * checking for updates...
	 */
	checkingForUpdates: () => LocalizedString
	/**
	 * check now
	 */
	checkNow: () => LocalizedString
	/**
	 * clear
	 */
	clear: () => LocalizedString
	/**
	 * confirm deletion
	 */
	confirmDeletion: () => LocalizedString
	/**
	 * connection type
	 */
	connectionType: () => LocalizedString
	/**
	 * identifies the connection in the models list
	 */
	connectionLabelHelp: () => LocalizedString
	/**
	 * connecting...
	 */
	connecting: () => LocalizedString
	/**
	 * connection has been verified and is ready to use
	 */
	connectionIsVerified: () => LocalizedString
	/**
	 * connection failed to verify, check the connection settings and try again
	 */
	connectionFailedToVerify: () => LocalizedString
	/**
	 * content
	 */
	content: () => LocalizedString
	/**
	 * controls
	 */
	controls: () => LocalizedString
	/**
	 * advanced controls are currently only available for ollama models
	 */
	controlsOnlyAvailableForOllama: () => LocalizedString
	/**
	 * copy
	 */
	copy: () => LocalizedString
	/**
	 * couldn't check for updates automatically
	 */
	couldntCheckForUpdates: () => LocalizedString
	/**
	 * couldn't connect to ollama server
	 */
	couldntConnectToOllamaServer: () => LocalizedString
	/**
	 * creating a tunnel
	 */
	creatingTunnel: () => LocalizedString
	/**
	 * current version
	 */
	currentVersion: () => LocalizedString
	/**
	 * danger zone
	 */
	dangerZone: () => LocalizedString
	/**
	 * dark
	 */
	dark: () => LocalizedString
	/**
	 * delete all knowledge
	 */
	deleteAllKnowledge: () => LocalizedString
	/**
	 * delete all sessions
	 */
	deleteAllSessions: () => LocalizedString
	/**
	 * delete all settings
	 */
	deleteAllSettings: () => LocalizedString
	/**
	 * delete knowledge
	 */
	deleteKnowledge: () => LocalizedString
	/**
	 * delete server
	 */
	deleteServer: () => LocalizedString
	/**
	 * delete session
	 */
	deleteSession: () => LocalizedString
	/**
	 * disconnected
	 */
	disconnected: () => LocalizedString
	/**
	 * dismiss
	 */
	dismiss: () => LocalizedString
	/**
	 * download model
	 */
	downloadModel: () => LocalizedString
	/**
	 * edit
	 */
	edit: () => LocalizedString
	/**
	 * no knowledge
	 */
	emptyKnowledge: () => LocalizedString
	/**
	 * no sessions
	 */
	emptySessions: () => LocalizedString
	/**
	 * error
	 */
	error: () => LocalizedString
	/**
	 * f16 kv
	 */
	f16Kv: () => LocalizedString
	/**
	 * frequency penalty
	 */
	frequencyPenalty: () => LocalizedString
	/**
	 * sorry, something went wrong
	 */
	genericError: () => LocalizedString
	/**
	 * go to downloads
	 */
	goToDownloads: () => LocalizedString
	/**
	 * go to knowledge
	 */
	goToKnowledge: () => LocalizedString
	/**
	 * go to releases
	 */
	goToReleases: () => LocalizedString
	/**
	 * how to obtain an api key from openai?
	 */
	howToObtainOpenAIKey: () => LocalizedString
	/**
	 * how to update docker container?
	 */
	howToUpdateDocker: () => LocalizedString
	/**
	 * interface
	 */
	'interface': () => LocalizedString
	/**
	 * there was an internal server error, please try again later
	 */
	internalServerError: () => LocalizedString
	/**
	 * you are on the latest version
	 */
	isCurrentVersionLatest: () => LocalizedString
	/**
	 * a newer version is available
	 */
	isLatestVersion: () => LocalizedString
	/**
	 * knowledge
	 */
	knowledge: () => LocalizedString
	/**
	 * knowledge saved
	 */
	knowledgeSaved: () => LocalizedString
	/**
	 * label
	 */
	label: () => LocalizedString
	/**
	 * language
	 */
	language: () => LocalizedString
	/**
	 * recently used models
	 */
	lastUsedModels: () => LocalizedString
	/**
	 * light
	 */
	light: () => LocalizedString
	/**
	 * low vram
	 */
	lowVram: () => LocalizedString
	/**
	 * main gpu
	 */
	mainGpu: () => LocalizedString
	/**
	 * message of the day
	 */
	messageOfTheDay: () => LocalizedString
	/**
	 * messages
	 */
	messages: () => LocalizedString
	/**
	 * min p
	 */
	minP: () => LocalizedString
	/**
	 * mirostat
	 */
	mirostat: () => LocalizedString
	/**
	 * mirostat eta
	 */
	mirostatEta: () => LocalizedString
	/**
	 * mirostat tau
	 */
	mirostatTau: () => LocalizedString
	/**
	 * model not found
	 */
	modelNotFound: () => LocalizedString
	/**
	 * model options
	 */
	modelOptions: () => LocalizedString
	/**
	 * {model} was downloaded
	 */
	modelWasDownloaded: (arg: { model: string }) => LocalizedString
	/**
	 * model names filter
	 */
	modelsFilter: () => LocalizedString
	/**
	 * hides model names that don't start with the filter
	 */
	modelsFilterHelp: () => LocalizedString
	/**
	 * motd
	 */
	motd: () => LocalizedString
	/**
	 * name
	 */
	name: () => LocalizedString
	/**
	 * new knowledge
	 */
	newKnowledge: () => LocalizedString
	/**
	 * new session
	 */
	newSession: () => LocalizedString
	/**
	 * no api key
	 */
	noApiKey: () => LocalizedString
	/**
	 * create new knowledge or choose one from the list
	 */
	noKnowledgeChosen: () => LocalizedString
	/**
	 * no recently used models
	 */
	noRecentModels: () => LocalizedString
	/**
	 * no server connections, add one to start
	 */
	noServerConnections: () => LocalizedString
	/**
	 * create a new session or choose an existing one from the list
	 */
	noSessionChosen: () => LocalizedString
	/**
	 * the page you are looking for does not exist
	 */
	notFound: () => LocalizedString
	/**
	 * num batch
	 */
	numBatch: () => LocalizedString
	/**
	 * context size
	 */
	numCtx: () => LocalizedString
	/**
	 * num gpu
	 */
	numGpu: () => LocalizedString
	/**
	 * num keep
	 */
	numKeep: () => LocalizedString
	/**
	 * num predict
	 */
	numPredict: () => LocalizedString
	/**
	 * number of threads
	 */
	numThread: () => LocalizedString
	/**
	 * numa
	 */
	numa: () => LocalizedString
	/**
	 * ollama
	 */
	ollama: () => LocalizedString
	/**
	 * ollama's library
	 */
	ollamaLibrary: () => LocalizedString
	/**
	 * openai: official api
	 */
	openAIOfficialAPI: () => LocalizedString
	/**
	 * openai: compatible servers (i.e. llama.cpp)
	 */
	openAICompatible: () => LocalizedString
	/**
	 * other models
	 */
	otherModels: () => LocalizedString
	/**
	 * penalize newline
	 */
	penalizeNewline: () => LocalizedString
	/**
	 * presence penalty
	 */
	presencePenalty: () => LocalizedString
	/**
	 * prompt
	 */
	prompt: () => LocalizedString
	/**
	 * write literally anything
	 */
	promptPlaceholder: () => LocalizedString
	/**
	 * pull model
	 */
	pullModel: () => LocalizedString
	/**
	 * model tag (e.g. llama3.1)
	 */
	pullModelPlaceholder: () => LocalizedString
	/**
	 * pulling model
	 */
	pullingModel: () => LocalizedString
	/**
	 * random
	 */
	random: () => LocalizedString
	/**
	 * reasoning
	 */
	reasoning: () => LocalizedString
	/**
	 * refresh to update
	 */
	refreshToUpdate: () => LocalizedString
	/**
	 * release history
	 */
	releaseHistory: () => LocalizedString
	/**
	 * repeat last n
	 */
	repeatLastN: () => LocalizedString
	/**
	 * repeat penalty
	 */
	repeatPenalty: () => LocalizedString
	/**
	 * retry
	 */
	retry: () => LocalizedString
	/**
	 * run
	 */
	run: () => LocalizedString
	/**
	 * re-verify
	 */
	reVerify: () => LocalizedString
	/**
	 * runtime options
	 */
	runtimeOptions: () => LocalizedString
	/**
	 * save
	 */
	save: () => LocalizedString
	/**
	 * search
	 */
	search: () => LocalizedString
	/**
	 * no results found
	 */
	searchEmpty: () => LocalizedString
	/**
	 * seed
	 */
	seed: () => LocalizedString
	/**
	 * see docs
	 */
	seeDocs: () => LocalizedString
	/**
	 * servers
	 */
	servers: () => LocalizedString
	/**
	 * server configuration was updated and needs to be re-verified in "settings"
	 */
	serverSettingsUpdated: () => LocalizedString
	/**
	 * session
	 */
	session: () => LocalizedString
	/**
	 * sessions
	 */
	sessions: () => LocalizedString
	/**
	 * settings
	 */
	settings: () => LocalizedString
	/**
	 * sorry, something went wrong
	 */
	somethingWentWrong: () => LocalizedString
	/**
	 * stop sequence
	 */
	stop: () => LocalizedString
	/**
	 * stop completion
	 */
	stopCompletion: () => LocalizedString
	/**
	 * stop response
	 */
	stopResponse: () => LocalizedString
	/**
	 * success
	 */
	success: () => LocalizedString
	/**
	 * system
	 */
	system: () => LocalizedString
	/**
	 * system prompt
	 */
	systemPrompt: () => LocalizedString
	/**
	 * temperature
	 */
	temperature: () => LocalizedString
	/**
	 * tfs z
	 */
	tfsZ: () => LocalizedString
	/**
	 * top k
	 */
	topK: () => LocalizedString
	/**
	 * top p
	 */
	topP: () => LocalizedString
	/**
	 * if you want to connect to an ollama server that is not available on {hostname} or {ip} try
	 */
	tryingToConnectNotLocalhost: (arg: { hostname: string, ip: string }) => LocalizedString
	/**
	 * typical p
	 */
	typicalP: () => LocalizedString
	/**
	 * use mlock
	 */
	useMlock: () => LocalizedString
	/**
	 * use mmap
	 */
	useMmap: () => LocalizedString
	/**
	 * use models from this server
	 */
	useModelsFromThisServer: () => LocalizedString
	/**
	 * verify
	 */
	verify: () => LocalizedString
	/**
	 * version
	 */
	version: () => LocalizedString
	/**
	 * vocab only
	 */
	vocabOnly: () => LocalizedString
	/**
	 * write a prompt to start a new session
	 */
	writePromptToStart: () => LocalizedString
	/**
	 * you
	 */
	you: () => LocalizedString
	/**
	 * content copied, but your connection is not private
	 */
	copiedNotPrivate: () => LocalizedString
	/**
	 * couldn't copy content. connection is not private
	 */
	notCopiedNotPrivate: () => LocalizedString
}

export type Formatters = {}
